---
- name: Install Custom Repository and Key
  hosts: localhost
  tasks:
    - name: Run install_apt_key_and_repo Module
      install_apt_key_and_repo:
        key_url: "KEY_URL"
        repo_url: "REPO_URL"
        distribution_codename: "jammy" # Replace with your distribution's codename
        repo_file: "REPO_NAME" # Replace with your repository name
